### PR TITLE
New source https://lazygirltranslations.com/

### PR DESCRIPTION
**Pull request by idMysteries**
There was no request to this site, this is my initiative

### CODE REVIEW

**Comment by idMysteries** [comment]
The chapter download function could possibly be implemented better.

**Comment by idMysteries** [comment]
This is more difficult to implement due to the fact that there can be any number of blocks of text in the chapters before the "Table of Contents".

**Comment by dipu-bd** [comment]
Merged and also fixed the chapter content parsing

**Comment by idMysteries** [comment]
> Merged and also fixed the chapter content parsing

``` py
 cover_img = soup.select_one('meta[property="og:image"]')
```
It's not like that in all books, so I didn't do it that way

https://lazygirltranslations.com/the-obsessive-shou-moves-on-rebirth/ has no og:image...

**Comment by idMysteries** [comment]
my code skipped this text.
изображение
изображение

**Comment by dipu-bd** [comment]
> > Merged and also fixed the chapter content parsing
> 
> ```python
>  cover_img = soup.select_one('meta[property="og:image"]')
> ```
> 
> It's not like that in all books, so I didn't do it that way
> 
> https://lazygirltranslations.com/the-obsessive-shou-moves-on-rebirth/ has no og:image...

I will revert it back then.

**Comment by dipu-bd** [comment]
> my code skipped this text.

I saw that the text has uneven new lines. I tried to remove those newlines.

**Comment by idMysteries** [comment]
@dipu-bd pep8 E201-202??
изображение
изображение

**Pull request merged**
