### PR TITLE
Update lnindo crawler and cfscrape util also add chapter info to filename

### PR DESCRIPTION
**Pull request by yudilee**
Update lnindo crawler
Update cfscrape in util to match latest update in https://github.com/Anorov/cloudflare-scrape to enable novelplanet crawler to work.
Add chapter info in file name for epub, mobi, docx and pdf file only if user not split book by volume

### CODE REVIEW

**Comment by dipu-bd** [comment]
I will merge it before the release

**Comment by dipu-bd** [comment]
The changes in lnindo crawler are crashing. Here is the bug report:

```
Traceback (most recent call last):
  File "/home/travis/build/dipu-bd/lightnovel-crawler/lncrawl/bots/test.py", line 38, in start
    self.test_crawler(link, entry)
  File "/home/travis/build/dipu-bd/lightnovel-crawler/lncrawl/bots/test.py", line 88, in test_crawler
    app.get_novel_info()
  File "/home/travis/build/dipu-bd/lightnovel-crawler/lncrawl/core/app.py", line 126, in get_novel_info
    self.crawler.read_novel_info()
  File "/home/travis/build/dipu-bd/lightnovel-crawler/lncrawl/spiders/lnindo.py", line 55, in read_novel_info
    if len(soup.body.contents[0].contents[7].contents[0].contents[16].contents[0].select('a')) not in wrong:
IndexError: list index out of range
```

**Comment by yudilee** [comment]
i'll check it

**Comment by dipu-bd** [comment]
what was wrong with the previous one- testing out all links in the body? why didn't it work?

**Comment by yudilee** [comment]
Hi @dipu-bd the website owner put message in html body in javanese language to not crawl their site. so i think better to remove support for lnindo for the next release. Thank you

**Comment by dipu-bd** [comment]
Ok. I am removing it.

**Comment by yudilee** [comment]
Thank you so much @dipu-bd

**Pull request merged**
