### PR TITLE
Pull dev branch

### PR DESCRIPTION
**Pull request by AncientCatz**

### CODE REVIEW

**Comment by dipu-bd** [comment]
I see that you have added back novelgo and yukinovel that was removed by the request of the owners. I am not sure about adding them back. It might upset the owners again.

**Comment by AncientCatz** [comment]
Cancel it, please

**Comment by dipu-bd** [comment]
@AncientCatz no need to cancel it. just update the __int__.py file adding them back to rejected_sources. I want to keep the other fixes

**Comment by dipu-bd** [comment]
@AncientCatz nvm, I updated `__init__.py` and merged your pull request. thanks for the fixes

**Pull request merged**
