### PR TITLE
Cleaner remove extra updates

### PR DESCRIPTION
**Pull request by idMysteries**

### CODE REVIEW

**Comment by dipu-bd** [comment]
How did you find all of them so soon!

**Comment by dipu-bd** [comment]
Did you use regex search?

**Comment by idMysteries** [comment]
Yeah

**Comment by idMysteries** [comment]
I'm using sublime text 4 :D

**Comment by idMysteries** [comment]
изображение

**Comment by idMysteries** [comment]
изображение
@dipu-bd fuuuuuuu so hard

**Comment by dipu-bd** [comment]
vscode has the same feature. It is fun to use.

**Pull request merged**
