### PR TITLE
New source https://usefulnovel.com/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1537

### CODE REVIEW

**Comment by idMysteries** [comment]
This code also doesn't work
@dipu-bd 

``` py
chapter_list_url = self.absolute_url('ajax/chapters', self.novel_url)
soup = self.post_soup(chapter_list_url, headers={'accept': '*/*'})
```

**Comment by idMysteries** [comment]
@dipu-bd it is not completed!!!! T_T

**Comment by dipu-bd** [comment]
@idMysteries Please give pull requrests only when it is completed, or mention that it is not ready yet.

**Comment by idMysteries** [comment]
@dipu-bd POST OK

**Pull request merged**
