### PR TITLE
Update scribblehub style

### PR DESCRIPTION
**Pull request by idMysteries**
border -> 2px
padding: 10px
width -> auto
margin: 0 auto
image

### CODE REVIEW

**Comment by idMysteries** [comment]
@dipu-bd wait...

**Comment by idMysteries** [comment]
You removes author notes?

**Comment by idMysteries** [comment]
I just think that the author's notes should not be deleted, because there is various useful (and not very) information there. For example, explanations to the chapter, pictures, etc.

**Comment by idMysteries** [comment]
As far as I remember, author's notes are not deleted for the webnovel.com site.

**Comment by idMysteries** [comment]
@dipu-bd can we change the div tag to table?
image

**Comment by idMysteries** [comment]
I just don't think that deleting author's notes is the right way.

**Comment by dipu-bd** [comment]
Author notes container spoiler. I removed it because of that. And in most cases when you are binge reading a story, it is sometimes distracting to see anything extra

**Comment by idMysteries** [comment]
If you haven't noticed, the spoiler is implemented there very simply and this program revealed it normally. On the first chapter there was a picture for example.
image

**Comment by dipu-bd** [comment]
Why would a caterpillar be relevant while reading a story though 😛

**Pull request merged**
