### PR TITLE
New template MangaStream

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1644

TODO:
- [x] #chapterlist
- [x] Chapters
- [ ] Volumes
- [x] Search
- [ ] Browser (CloudFlare bypass)
- [x] More sources

Issues:
https://github.com/dipu-bd/lightnovel-crawler/issues/659
https://github.com/dipu-bd/lightnovel-crawler/issues/1539
https://github.com/dipu-bd/lightnovel-crawler/issues/1676
https://github.com/dipu-bd/lightnovel-crawler/issues/1687

### CODE REVIEW

**Comment by idMysteries** [comment]
@dipu-bd help me pls with browser. ``if get_soup error -> try browser`

**Comment by dipu-bd** [comment]
> @dipu-bd help me pls with browser. `if get_soup error -> try browser`

sure, I will check.

**Comment by dipu-bd** [comment]
Is this ready for merge, or do you want to work on it more?

**Comment by idMysteries** [comment]
> Is this ready for merge, or do you want to work on it more?

browseeeer!

**Comment by dipu-bd** [comment]
I will work on the browser. If it is done by you, I will start review and merging process

**Comment by idMysteries** [comment]
> I will work on the browser. If it is done by you, I will start review and merging process

I'm thinking about doing volumes or not. Some sites have volumes. If you have 30 minutes to wait, then I will make volumes of the book.

**Comment by dipu-bd** [comment]
I can wait. No hurry. I do not have time to do the review and other changes today anyway. Take your time.

**Comment by idMysteries** [comment]
@dipu-bd pls don't edit this template. I'm working now. Pls wait for new commit!

**Comment by idMysteries** [comment]
@dipu-bd ohhh.... Do I understand correctly that the ChapterWithVolumeSoupTemplate template only works if there are volumes, and if there are none, will there be an error?

**Comment by idMysteries** [comment]
@dipu-bd This turned out to be harder than I thought...

**Comment by dipu-bd** [comment]
> @dipu-bd This turned out to be harder than I thought...

can you explain your use case a bit more? what did you expect to get?

**Comment by dipu-bd** [comment]
Yes. That's what the template is for. If you want autogenerated volumes you can use ChapterOnly

**Comment by idMysteries** [comment]
@dipu-bd Aren't you listening to me at all? I wrote that there are sites with volumes, and there are without this template.

**Comment by dipu-bd** [comment]
> @dipu-bd Aren't you listening to me at all? I wrote that there are sites with volumes, and there are without this template.

Sorry, I may not have been clear in what I wanted to say. You said some sites have volumes and some don't and ChapterWithVolume is not working for you. I wanted to know what changes you propose to make it work? Maybe we can make another template that suit your current use case

**Comment by idMysteries** [comment]
@dipu-bd ChapterWithVolume does not work because volumes are required.

**Comment by dipu-bd** [comment]
Then what would work? Do you have a suggestion?

**Comment by dipu-bd** [comment]
Since I am not working with the template, I don't know lots of details about it. I can't provide you useful suggestions here. I can only say if it can be done or not after hearing your suggestions

**Comment by idMysteries** [comment]
``` py
class ChapterWithVolumeSoupTemplate(GeneralSoupTemplate):
    def parse_chapter_list(self, soup: BeautifulSoup) -> None:
        volumes = self.select_volume_tags(soup)
        if volumes 
          for vol in self.select_volume_tags(soup):
              if not isinstance(vol, Tag):
                   continue
               self.process_volumes(vol)
          else pase chapters...???
    def process_volumes(self, vol: Tag) -> None:
        vol_id = len(self.volumes) + 1
        vol_item = self.parse_volume_item(vol, vol_id)
        self.volumes.append(vol_item)
        for tag in self.select_chapter_tags(vol, vol_item):
            next_id = len(self.chapters) + 1
            item = self.parse_chapter_item(tag, next_id, vol_item)
            item.volume = vol_id
            self.chapters.append(item)

```

**Comment by dipu-bd** [comment]
If I understand correctly, you are suggesting to get chapters without volumes if volumes are not present?

**Comment by idMysteries** [comment]
> If I understand correctly, you are suggesting to get chapters without volumes if volumes are not present?

YES!

**Comment by dipu-bd** [comment]
ChapterOnly has no volumes, ChapterWithVolumes has mandatory volumes. If you need both, then just create another template, e.g. OptionalVolumeSoupTemplate

**Comment by dipu-bd** [comment]
Or you can use ChapterWithVolume and override the process_volume logic to fit your use case

**Comment by dipu-bd** [comment]
> > ChapterOnly has no volumes, ChapterWithVolumes has mandatory volumes. If you need both, then just create another template, e.g. OptionalVolumeSoupTemplate
> 
> Then maybe it's better to merge them?

It's not harming anybody if they are separate. Sometimes in future we may need this abstraction. As I see it, having more templates is better for the future.

**Comment by idMysteries** [comment]
Why do I need ChapterOnly if there is an OptionalVolume?

**Comment by idMysteries** [comment]
OptionalVolume is universal template!

**Comment by dipu-bd** [comment]
> OptionalVolume is universal template!

Do you want parse_volume_item and select_volume_tags to be mandatory methods to be implemented?

**Comment by dipu-bd** [comment]
We can write OptionalVolumr template and extends ChapterOnly and ChapterWithVolume from it

**Comment by idMysteries** [comment]
> > OptionalVolume is universal template!
> 
> Do you want parse_volume_item and select_volume_tags to be mandatory methods to be implemented?

No... I'm not python-giga-master-dev like you, sorry!

**Comment by dipu-bd** [comment]
> > > OptionalVolume is universal template!
> > 
> > 
> > Do you want parse_volume_item and select_volume_tags to be mandatory methods to be implemented?
> 
> No... I'm not python-giga-master-dev like you, sorry!
> 
> Default?
> 
> ```python
> def select_volume_tags 
> return None
> ```

Maybe return an empty list. I can't tell without experimenting. 

Take your time, no rush. Don't let it make you frustrated. 😇

**Comment by idMysteries** [comment]
It's night in Mother Russia. Goodnight!

**Comment by dipu-bd** [comment]
> It's night in Mother Russia. Goodnight!

It's also 1am here, and I have office tomorrow. Goodnight!

**Comment by mesmerlord** [comment]
For the browser, cloudflare bypass, maybe we can use : https://github.com/ultrafunkamsterdam/undetected-chromedriver instead of normal selenium.

**Comment by idMysteries** [comment]
> For the browser, cloudflare bypass, maybe we can use : https://github.com/ultrafunkamsterdam/undetected-chromedriver instead of normal selenium.

we are using undetected-chromedriver....

**Comment by dipu-bd** [comment]
@idMysteries I have enabled support for optional volumes. Please check https://github.com/dipu-bd/lightnovel-crawler/commit/2766ad76aa62acdfde31e18091c5def73f47ca6c

**Pull request merged**
