### PR TITLE
added https://hotnovelfull.com/

### PR DESCRIPTION
**Pull request by SirGryphin**
Clone site of "readnovelfull.py" everything working but for some reason it won't download cover images. I've tried multiple different ways.

### CODE REVIEW

**Comment by idMysteries** [comment]
The cover image is downloaded normally.

**Review by idMysteries — APPROVED** [review]

**Comment by SirGryphin** [comment]
@idMysteries might just be the novel, I'm trying then. but for me the cover was missing. At least it works  😃

**Comment by idMysteries** [comment]
Have you updated the code to version 2.32? Maybe that's the problem? It works for me, I have synchronized the repositories.

**Comment by idMysteries** [comment]
I'm too dumb to understand the difference between our realities. It doesn't work for you, it works for me. Is it magic, science, many-worlds interpretation?
Lately I feel like an idiot. Sorry I'm Russian. Т_Т

**Pull request merged**
