### PR TITLE
[README] Additional Information

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1499
Maybe it will help someone

### CODE REVIEW

**Comment by dipu-bd** [comment]
why is setup.py appears to be modified in your changes?

**Comment by idMysteries** [comment]
github bug maybe
It's fork of the "master" branch

**Comment by idMysteries** [comment]
It looks like I was able to fix this problem

**Comment by idMysteries** [comment]
Idk why. It looks like this is because I used the master branch.
изображение

**Pull request merged**
