### PR TITLE
Merge `novelpub.com` and `lightnovelpub.com`

### PR DESCRIPTION
**Pull request by jere344**
They are exactly the same
So #1607 fix this one too

#1605

### CODE REVIEW

**Comment by dipu-bd** [comment]
Please do not remove a source file. It may create issues for auto-updates. Also, this does not solves the search URL issue for lightnovelpub.com

**Comment by jere344** [comment]
Ok I didn't know about not removing source. It's just that it was weird to have `novelpub` and `lightnovelpub` in different files while `lightnovelpub` with `lightnovelworld`. The 3 are the same.

And I checked, before it returned nothing, now we get search results, but they are wrong. I will look into it.
image

**Comment by jere344** [comment]
So `lightnovelpub` use a post request to `https://www.lightnovelpub.com/lnsearchlive` with `inputContent=query` but it use cloudflare and cloudscraper does not work so I give up

**Comment by dipu-bd** [comment]
> It's just that it was weird to have `novelpub` and `lightnovelpub` in different files while `lightnovelpub` is with `lightnovelworld`. The 3 are the same

That I know. A new way to make crawlers will be introduced in the next version. Crawlers will be able to use predefined templates. So they will become shorter and it will solve these problems.

**Comment by dipu-bd** [comment]
> So `lightnovelpub` use a post request to `https://www.lightnovelpub.com/lnsearchlive` with `inputContent=query` but it use cloudflare and cloudscraper does not work so I give up

I'll check this out. Thanks for leading it so far

**Comment by dipu-bd** [comment]
Fixed in dev

**Pull request closed without merging**
