### PR TITLE
Correcting small error in chapter.xhtml

### PR DESCRIPTION
**Pull request by zerty**

### CODE REVIEW

**Comment by dipu-bd** [comment]
Why do you think it is an error?

**Comment by zerty** [comment]
When opening with calibre, style is not applied
image

**Comment by dipu-bd** [comment]
Why are you directly opening xhtml files? 

In new structure of epub file, I am putting chapters into separate `chapter` folder. The `style.css` is defined one level above the folder. Therefore it is required to use `../style.css`

**Comment by zerty** [comment]
I am oppening the Epub.
For some reason the template is incorrectly applied in the cover which is in the root and not in chapter folder.
The resulting xhtml has the head from the chapter template for unknown reasons
I am guessing it is happening because of some weird behavior in the ebooklib module

**Comment by dipu-bd** [comment]
> The resulting xhtml has the head from the chapter template for unknown reasons
> I am guessing it is happening because of some weird behavior in the ebooklib module

I noticed. This is definitely an issue with ebooklib. I have to do some workaround to fix it.

**Pull request closed without merging**
