### PR TITLE
[403 error] New source https://novel35.com/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1664

### CODE REVIEW

**Comment by idMysteries** [comment]
@dipu-bd 
The user wrote that there is no CloudFlare protection.
So I was a fool to believe.
As a result, I got error 403.

I hope I didn't write this shit code for nothing.

**Comment by idMysteries** [comment]
@dipu-bd don't trust the users!

**Comment by dipu-bd** [comment]
I got the browser thing figured out. It is in testing now. No worry about cloudflare anymore :D

**Comment by idMysteries** [comment]
And how to make requests through the chrome driver?

**Pull request merged**
