### PR TITLE
New source : https://www.wuxianovelhub.com/

### PR DESCRIPTION
**Pull request by zerty**

### CODE REVIEW

**Comment by idMysteries** [comment]
Oh my God...

**Comment by zerty** [comment]
I don't understand, if there is a problem just close the pull request, i ve made another one by error but i closed it before anyone could merge ...

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/blob/dev/sources/en/l/ltnovel.py

**Comment by idMysteries** [comment]
Just replace https://www.ltnovel.com/ to https://www.wuxianovelhub.com/

**Comment by idMysteries** [comment]
Before you write the code, check if we have it. You were just wasting your time.

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/search?q=fy%2Cphp

**Comment by zerty** [comment]
My bad, I had only checked the URL, closing

**Comment by idMysteries** [comment]
I'm not scolding you. It's just that we're all mortals, there's no need to waste time.
I have a war in my country, mobilization, and I know how important time is. :heart:

**Comment by dipu-bd** [comment]
@zerty  You can modify the existing source and add this entry to base_url list: `https://www.wuxianovelhub.com/` 

I am looking forward to see another PR from you.

**Pull request closed without merging**
