### PR TITLE
New source https://snowycodex.com/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/653

@dipu-bd code review needed. I'm using SinglePageSoupTemplate first time
Cover 403 error

### CODE REVIEW

**Comment by dipu-bd** [comment]
I checked the 403 error issue without cloudscraper. Strangely it works with normal Session. But not with cloudscraper.

**Comment by dipu-bd** [comment]
Figured it out. The HOST header was causing this issue.

**Comment by dipu-bd** [comment]
Damn.. this was the root cause for wuxiaworld crawler failure. Now it is working again.

**Comment by idMysteries** [comment]
Ahahahahahaha

**Pull request merged**
