### PR TITLE
Ln 1341 proxy example

### PR DESCRIPTION
**Pull request by mesmerlord**
The best way this could be implemented is if you can instantiate a Crawler with "self.new_proxies" being a list. And on get request, you can do 
```
splitprox = random.choice(proxiesToList)[0].split(":")
proxyy = f'http://{splitprox[2]}:{splitprox[3]}@{splitprox[0]}:{splitprox[1]}'
proxies  = {'http':proxyy, 'https':proxyy}
kwargs['proxies'] = proxies
```
Feel free to close this PR without merging as this is just example code

### CODE REVIEW

**Comment by mesmerlord** [comment]
Relates to https://github.com/dipu-bd/lightnovel-crawler/issues/1341

**Comment by dipu-bd** [comment]
I would rather add an argument option to enter the file path for proxy list. A hard-coded file is not very usable

**Comment by mesmerlord** [comment]
Right sorry that was two different approaches I was trying to show. I think easiest to implement is probably just a field in the main crawler class itself. I'll update the PR, please approve and merge if possible

**Comment by mesmerlord** [comment]
Fixed now. If you can have a look, that'd be great

**Pull request merged**
