### PR TITLE
Create 69shu.py

### PR DESCRIPTION
**Pull request by jere344**
I had to overwrite get_source to make the request because I didn't know how to deal with the encoding. The other Chinese sources works fine from the start tho, I don't know why

### CODE REVIEW

**Comment by jere344** [comment]
The issue with encoding is that I need to set the encoding of the response to `gbk` before it is parsed to a soup.
I don't know if there is already  a way to do that, if not I can just add an `encoding` argument to `Scraper` `get_soup()` then `make_soup` like so :
```py
def make_soup(
        self,
        data: Union[Response, bytes, str],
        parser: Optional[str] = None,
        encoding="utf8"
    ) -> BeautifulSoup:
        if isinstance(data, Response):
            html = data.content.decode(encoding, "ignore")
        elif isinstance(data, bytes):
            html = data.decode(encoding, "ignore")
        elif isinstance(data, str):
            html = str(data)
        else:
            raise LNException("Could not parse response")
        return BeautifulSoup(html, features=parser or self.parser)
```

current :
```py
def make_soup(
        self,
        data: Union[Response, bytes, str],
        parser: Optional[str] = None,
    ) -> BeautifulSoup:
        if isinstance(data, Response):
            html = data.content.decode("utf8", "ignore")
        elif isinstance(data, bytes):
            html = data.decode("utf8", "ignore")
        elif isinstance(data, str):
            html = str(data)
        else:
            raise LNException("Could not parse response")
        return BeautifulSoup(html, features=parser or self.parser)
```

**Comment by zGadli** [comment]
So, I researched this a little bit. I see two solutions. We make a check on the source for its encoding by looking for charset in the <head></head>. In this case we get "gbk" for 69shu.com and then use a gbk decoding option. 

The other solution would be to use a library to detect encoding. for example: chardet or multilingual.

It would look something like tihs:

```
pip install chardet
import chardet

def detect_encoding(byte_data):
    result = chardet.detect(byte_data)
    return result['encoding']

byte_data = b'\xe8\xbf\x99\xe5\xa3\xb0\xe9\x9f\xb3'  # Example bytes data
detected_encoding = detect_encoding(byte_data)
print(detected_encoding)  # Output: utf-8

```

**Comment by zGadli** [comment]
Just tested using chardet in colab. It can't detect "gbk" encoding. Seems like chardet option is the only one.

**Comment by zGadli** [comment]
This code seems to get the job done.

```
import requests
from bs4 import BeautifulSoup

url = 'https://www.69shu.com/txt/C48057.htm'  # Replace with the URL you want to check

response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, 'html.parser')

meta_tag = soup.find('meta', {'charset': True})

if meta_tag:
    charset = meta_tag['charset']
    print('Charset:', charset)
else:
    print('Charset information not found in meta tag.')

```
Tested in google colab.

**Pull request merged**
