### PR TITLE
New source https://novelsala.com/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1520

@dipu-bd can you help me?

### CODE REVIEW

**Comment by idMysteries** [comment]
Chapter ex.:
https://novelsala.com/_next/data/MmTfa7fKwmG7opf6oZ4Ga/en/novel/fantasy-god-level-store-manager/chapter-1.json

Book data ex.:
https://novelsala.com/_next/data/MmTfa7fKwmG7opf6oZ4Ga/en/novel/fantasy-god-level-store-manager/chapters.json

**Comment by idMysteries** [comment]
This site uses graphql.

**Comment by idMysteries** [comment]
Holy shit, I DID IT!!!

**Comment by idMysteries** [comment]
@dipu-bd I wish you were messing with this site. But my inner masochist turned on in me.
Now you can refine my bad code.

**Comment by idMysteries** [comment]
@dipu-bd search works fine!
изображение

**Comment by idMysteries** [comment]
@dipu-bd I tried to split graphql_body into several lines, but the error 400 bad request was returned. Maybe you can do it

**Comment by idMysteries** [comment]
@dipu-bd I just noticed that you have a similar code T_T. Although it differs from mine a lot

https://github.com/dipu-bd/lightnovel-crawler/blob/dev/sources/en/l/lightnovelme.py

**Comment by dipu-bd** [comment]
The code quality seems good to me. Good work.

**Pull request merged**
