### PR TITLE
Create novelLight

### PR DESCRIPTION
**Pull request by Ankush12345567**
How to get this source added please someone explain the next step

### CODE REVIEW

**Comment by Magos-Technicus** [comment]
dude, i can help you
there's a way to do this, a genious madman created an automatic source creation and it's actually really easy to use, you need to 
follow the tutorial that is in the description though
but alas, it can be not that simple
sometimes it doesnt work, and sometimes when it works it needs some tweaks to make it work flawlessly, but my god it's a very amazing and handy tool, it makes your job WAY easier than not using it.
 
Just send the url of the site so i can try this weekend, and please delete the other pull request that you created for this site, since you created 2 and we only need one, anyway, happy holidays for ya, i hope i can be santa claus and upload this source before 25/12 : )

**Comment by Magos-Technicus** [comment]
duuuuude you need to change the brench to dev's brench, dev's brench
also, happy holidays ^^ and thanks for the help !

**Comment by Magos-Technicus** [comment]
you need to change the brench to dev's brench
also, happy holidays ^^ and thanks for the help !

**Comment by dipu-bd** [comment]
I have merged your previous PR. sorry for the delay, I was busy with other tasks

**Pull request merged**
