### PR TITLE
Use chardet by default to find the encoding

### PR DESCRIPTION
**Pull request by jere344**
See #2022 for context

I tried a few different sources, and it did not seem to cause any issues. 
I still added it as an argument to be able to overwrite it if chardet can't determine encoding.

### CODE REVIEW

**Comment by zGadli** [comment]
Check if sources: 69shu.com works with the code.

**Comment by jere344** [comment]
When I remove the custom get_soup It works with 69shu.com with no issue

**Comment by jere344** [comment]
Chardet seems to make a lot of mistake in finding the encoding, I'm not sure if it should get merged. For example it messed up the encoding here : `https://chrysanthemumgarden.com/novel-tl/ygbg/ygbg-1/`

**Comment by dipu-bd** [comment]
I merged this to enable passing custom encoding

**Pull request merged**
