### PR TITLE
Added manga sources

### PR DESCRIPTION
**Pull request by SirGryphin**
I've not posted a source file in a while and the layout and how it works has changed within the last year. I'm not sure what other files I'm meant to edit.

It use to be the README.md to add the source to the "Supported Sites" and that's it. Now there some kind of _index json that I see you edit in latest PR. Could you explain what I need to do when add sources now or is it okay just to PR the single python file.

**UPDATE:** I've add a few manga sites as I'm downloading some for a friend. If there not allowed for support sites please let me know and I will stop pushing them.

### CODE REVIEW

**Comment by SirGryphin** [comment]
@UltraStudioLTD 
Yeah, I thought they was allowed, there is a feature in light novel crawler that supports them and it works okay.

**Comment by UltraStudioLTD** [comment]
@dipu-bd if this PR gets accepted, you should rename this project (**lightnovel-crawler**) to **manganovel-crawler** or something like that

**Comment by UltraStudioLTD** [comment]
@SirGryphin it just doesn't sit well with current name of project which is novels-only

**Comment by SirGryphin** [comment]
@UltraStudioLTD If @dipu-bd wants to remove it, I see no problem. I was just never told not to do manga sites, I'm 95% sure there are other sources/sites already added with manga. If it's against rules or recommend not to somewhere and I missed it please let me know. I don't want to cause any problems.

**Comment by dipu-bd** [comment]
@SirGryphin With new structure, you do not need to edit any README.md or index.json files. They are autogenerated. Just update the crawler files in `sources` folder. After you commit to dev branch, a auto commit will happen to update README.md, and index.json

**Comment by dipu-bd** [comment]
@UltraStudioLTD  There is no rule saying it can't have manga just because the project name starts with `lightnovel`. Changing project name is a bit of a hassle.

**Comment by UltraStudioLTD** [comment]
> @UltraStudioLTD There is no rule saying it can't have manga just because the project name starts with `lightnovel`. Changing project name is a bit of a hassle.

Alright

**Comment by SirGryphin** [comment]
@dipu-bd I've switch to Dev, sorry about that. Also what your saying is.. I just put my source file e.g `LightNovelSite.py` into `Sources > en > L` and it just automatically does the rest?

**Pull request closed without merging**
