### PR TITLE
Minor fix 

### PR DESCRIPTION
**Pull request by yudilee**
this pull request contain minor fix
- fix volume title in wuxiaco crawler
- fix heading for volume
- fix telegram bot because 50 mb file limit for uploading in bot api
- adding description about file format output supported by discord bot

### CODE REVIEW

**Comment by dipu-bd** [comment]
why did you call `make_epubs` in `binders/__init__.py`? I made sure that outputs['epub'] is always available for epub dependencies. it is not needed to generate epubs everytime for other formats.

**Comment by yudilee** [comment]
Because both telegram and discord bot sent chosen output format and epub too. I want only chosen format sent

**Comment by dipu-bd** [comment]
i fixed it in my last push. `app.output_formats` is not being modified anymore. `outputs` is a dictionary that contains all the generated file list. i am just returning it from the method.

**Comment by dipu-bd** [comment]
ah wait. it is being modified as a reference. damn

**Comment by dipu-bd** [comment]
i made the necessary fix in init.py file. revert your changes in init.py here. i will merge it then

**Comment by yudilee** [comment]
Thank you so much

**Comment by yudilee** [comment]
> i made the necessary fix in init.py file. revert your changes in init.py here. i will merge it then

Done reverting, just install github desktop to revert it. that was great experience to use github desktop

**Pull request closed without merging**
