### PR TITLE
[403 ERROR] New source https://noblemtl.com/

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1539

### CODE REVIEW

**Comment by idMysteries** [comment]
@dipu-bd idk how to fix it
изображение

**Comment by idMysteries** [comment]
@dipu-bd Crawler should work. If it works for you, then you can merge this code

**Comment by dipu-bd** [comment]
Were you able to make any successful download?

**Comment by idMysteries** [comment]
I have tested different versions of the code and always get a 403 error.

**Comment by idMysteries** [comment]
Cloudflare T_T

**Comment by idMysteries** [comment]
изображение

**Comment by idMysteries** [comment]
@dipu-bd sorry, I'm stupid.

**Comment by dipu-bd** [comment]
Let's not add a source unless we get a succesfull download. We should keep it pending or add to rejected sources

**Comment by idMysteries** [comment]
@dipu-bd google colab
изображение

**Comment by idMysteries** [comment]
Maybe it's because of the proxy?

**Comment by dipu-bd** [comment]
Looks like it has merge conflicts. Can you close this and make a fresh pull request?

**Comment by idMysteries** [comment]
After the update, error 403. CloudFlare T_T

**Pull request closed without merging**
