### PR TITLE
Fix novelupdates [In process]

### PR DESCRIPTION
**Pull request by CryZFix**
Changed "action" key in ajax
#2241

### CODE REVIEW

**Comment by greenaar** [comment]
Worked, but now fails again. I suspect that means it changed again? How did you determine the new value? (ie so that I know where to look?) Thanks!

**Comment by CryZFix** [comment]
Hurried with the conclusions, the problem is local for the book out of the issue. I'm looking at what can be done.

**Comment by picnixz** [comment]
The issue is that the AJAX request needs special cookies. I had a quick look at what was done when you are logged in to NU and requested the full chapters list. When I was logged off, you can't view the full chapters list. After some trials and errors, I deduced that you need to query the API with a cookie acknowledging that you are connected to NU. 

I suspect that for guests, rendering is done on the server side and that a somewhat fake cookie is being used or the check is by-passed if the request is internal (don't know how it's implemented). 

As such, a solution would be to tell users to create a NU account and we would use the cookies used for that (though thezy need to truste how we use their cookies then). I don't see another way to do it since the URLs to the chapters are only available if you are connected (not all endpoints require you to be connected though).

**Comment by dipu-bd** [comment]
The title is marked as In process. Is it still correct?

**Pull request closed without merging**
