### PR TITLE
new domain for 69shuba

### PR DESCRIPTION
**Pull request by nd2024**
-- https://www.69xinshu.com/

#2219

### CODE REVIEW

**Comment by neoryd** [comment]
@dipu-bd

**Comment by dipu-bd** [comment]
why did you modify wuxiacom.py file? I do not see it necessary

**Comment by neoryd** [comment]
> why did you modify wuxiacom.py file? I do not see it necessary

because it fail on lint test on main branch.

**Comment by neoryd** [comment]
> why did you modify wuxiacom.py file? I do not see it necessary

because it fail the lint test on main branch.

**Comment by dipu-bd** [comment]
ignore the lint errors. just remove your changes to the file, and make a commit.

**Comment by neoryd** [comment]
that should be done? sorry, i'm new

**Comment by dipu-bd** [comment]
It is still showing the file in the commit : https://github.com/dipu-bd/lightnovel-crawler/pull/2223/files

You can make new branch from dev, put your changes there, and make a PR here again. It'll reduce some complexity.

**Pull request closed without merging**
