### PR TITLE
Fusing several crawler and adding sources

### PR DESCRIPTION
**Pull request by zerty**
* Fusing crawler for ltnovel, novelmt, readwn into novelmtl
* added bunch of other site working the same
* Search is working on all sites
* TODO: Login and logout depending on root url

### CODE REVIEW

**Comment by idMysteries** [comment]
Wtf are you doing???
https://github.com/dipu-bd/lightnovel-crawler/pull/1625
Why are you deleting other sites? These are not mirrors of a single domain. There are different novels on them.

**Comment by idMysteries** [comment]
If you make a template, then the template needs to be done differently.

**Comment by zerty** [comment]
also #1434 #933

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/tree/dev/lncrawl/templates
https://github.com/dipu-bd/lightnovel-crawler/blob/dev/lncrawl/templates/madara.py

**Comment by zerty** [comment]
ok ill redo as template then

**Comment by idMysteries** [comment]
https://github.com/dipu-bd/lightnovel-crawler/blob/dev/sources/ru/bestmanga.py

**Comment by idMysteries** [comment]
Please use this code for new template https://github.com/dipu-bd/lightnovel-crawler/pull/1625

**Comment by dipu-bd** [comment]
@zerty Thanks for trying your best. Please make sure that you are sending PR to `dev` branch.

**Comment by dipu-bd** [comment]
> Wtf are you doing??? #1625 Why are you deleting other sites? These are not mirrors of a single domain. There are different novels on them.

Well, I do not think it was his fault. He was originally working on the source, and would not know if you were also working on it parallely. #1625 can be used as a good template. @zerty if you are interested to work on it, you can have a go at it.

Check for exaple:
- https://github.com/SirGryphin/lightnovel-crawler/blob/dev/lncrawl/templates/madara.py
- https://github.com/SirGryphin/lightnovel-crawler/blob/dev/sources/en/m/mangarockteam.py

**Comment by idMysteries** [comment]
@zerty @dipu-bd I can quickly write a template for these sites.

**Comment by dipu-bd** [comment]
@zerty Do you want to leave it to @idMysteries?

**Comment by zerty** [comment]
Already done but still the search is not working

**Comment by idMysteries** [comment]
@zerty PR please. I'll review your code

**Comment by zerty** [comment]
f95307517bfd6c2067c534c80ed44d4e41ac1858 still working on the search

**Pull request closed without merging**
