### PR TITLE
Fix webnovel incorrect url in the search list

### PR DESCRIPTION
**Pull request by idMysteries**
Ohhh

### CODE REVIEW

**Comment by dipu-bd** [comment]
webnovel search seems to be working fine as it is now.

**Comment by idMysteries** [comment]
No, home_url is bad if you try to download webnovel from search list

**Comment by idMysteries** [comment]
home_url will be https://www.webnovel.com/book/NOVEL_ID?encryptType=3&_fsae=0

**Review by idMysteries — COMMENTED** [review]
Fix wrong novel_id after search

**Comment by dipu-bd** [comment]
Oh, I got it

**Pull request merged**
