### PR TITLE
Novelupdates.com

### PR DESCRIPTION
**Pull request by SirGryphin**
Not sure if this site is allowed or not, if not just close this and let me know.

Tested: https://www.novelupdates.com/series/sand-sculpture-demon-king-online-farming/

I created a simple source file for novels that link to a blog without a table of content. Like the one listed above. Without using novelupdates to grab  chapters I can't think of another way to get novel from blog.

Update: I know there will be a lot of junk/bad text depending on what blog novelupdates links you to for each novel but it's better than nothing.

### CODE REVIEW

**Review by jere344 — CHANGES_REQUESTED** [review]
Sometimes novelupdates has several translations for the same chapter, missing chapters or unordered chapters. I think you should try to use the chapter number as id instead of using the order shown on novelupdates

**Comment by SirGryphin** [comment]
@jere344 What something like this?

```python
self.chapters.append( 
     Chapter( 
         id=a["title"].strip() + 1, 
         title=a["title"].strip(), 
         url=self.absolute_url(a["href"]), 
     ) 
 ) 
```

**Comment by jere344** [comment]
@kuwoyuki there is a lot of article reader like app on android that can pull text from any website. I used one for a long time, and was it good enough 70% of the time.
I would really like a novelupdate souce as it has the most content from small fan translation group, even if it does not always work.

But yes the source as is will only work for one website, so it need to be improved.

**Comment by idMysteries** [comment]
What? https://awanderingpotato.com/ for this novel please!

This site is just a redirect to other sites. You should make a separate crawler for each site.

**Comment by jere344** [comment]
@idMysteries making a crawler for each blog with only 1-2 novel isn't worth it, so I think that making an universal crawler for chapter content only using novelupdates metadata can be great.

**Comment by idMysteries** [comment]
> @idMysteries making a crawler for each blog with only 1-2 novel isn't worth it, so I think that making an universal crawler for chapter content only using novelupdates metadata can be great.

The current "lightnovel-crawler" code is designed for the fact that you will use one crawler class for one site or template.

**Comment by kuwoyuki** [comment]
> @idMysteries making a crawler for each blog with only 1-2 novel isn't worth it, so I think that making an universal crawler for chapter content only using novelupdates metadata can be great.

It can obviously work but there's a good chance there will be a lot of broken novels because either the blog DOM is just too messed us for us to analyze it (a lot are) or the link is just dead.  
There are libs used for Web Readability mode such as [mozzila's readability](https://github.com/mozilla/readability) which do a somewhat decent job at analyzing the page DOM and finding the node that is most likely to be the article/content, haven't looked whether there's a Python alternative.

**Comment by jere344** [comment]
> It can obviously work but there's a good chance there will be a lot of broken novels because either the blog DOM is just too messed us for us to analyze it (a lot are) or the link is just dead. Also a good way to do this would be to obviously first attempt to use the existing lncrawl's sources if the link matches one and then fallback to the universal. There are libs used for Web Readability mode such as [mozzila's readability](https://github.com/mozilla/readability) which do a somewhat decent job at analyzing the page DOM and finding the node that is most likely to be the article/content, haven't looked whether there's a Python alternative.

Yes that's what I was thinking about. And I think the benefit of having a novelupdates source which has a lot of original content and the best metadata outweigh the issues with broken novels. But like @idMysteries said it is different from every other sources, so we need @dipu-bd 's opinion.

**Comment by SirGryphin** [comment]
I've been working on a template using the new template system for blog sites, I'm hoping to get it working then use it for novelupdates and see how it works. But to be honest I created this and thought I could update it to work with certain sites, The only time I really need to crawl from NU is when the blog sites doesn't have a TOC page as I would otherwise use something like Web2epub as it will just grab everything from TOC on small blog sites, it quicker and easier than writing a source file for each little blog that pops up.

**Comment by dipu-bd** [comment]
Adding support for novelupdates would give a lot of benefits with chapter indexing and searching novels. Since we have now templates, we can make a general template for novelupdates. Like @kuwoyuki suggested, we can use the exisiting crawlers for parsing chapter contents. And as a fallback we can use a DOM extractor like @jere344 suggested.

With a general novelupdates template it will become much easier to support new sources. We can use the `lookup` bot to make new crawlers very fast. In this case, we need the novelupdates link corresponding to a novel link. I think this can be done using the search of novelupdates.

**Comment by dipu-bd** [comment]
Closing this PR for #1754

**Pull request closed without merging**
