### PR TITLE
Add https://sj.uukanshu.com/ 

### PR DESCRIPTION
**Pull request by idMysteries**
https://github.com/dipu-bd/lightnovel-crawler/issues/1457
https://github.com/dipu-bd/lightnovel-crawler/issues/515

TODO:
- [x] Search
- [x] Volumes

### CODE REVIEW

**Comment by idMysteries** [comment]
Everything seems to be ready. But due to the fact that it is Chinese, you need to have Chinese in the OS to search.
image

**Comment by dipu-bd** [comment]
> But due to the fact that it is Chinese, you need to have Chinese in the OS to search.

You have to enable the utf-8 encoding in the command prompt to see them. It is better to use the Windows Terminal if you are on windows.

**Comment by dipu-bd** [comment]
I see that you left one task unchecked:  

> Better format text maybe

Is this PR ready to merge?

**Comment by idMysteries** [comment]
I didn't notice any problems with format_text
If one of the users finds it, I will fix it later

**Pull request merged**
