### PR TITLE
asianhobbyist

### PR DESCRIPTION
**Pull request by SirGryphin**
Noticed it didn't get  chapters anymore, guess they updated site layout. I've fixed that but now with new layout novel cover doesn't download I guess it because it actually redirects/links to novel updates cdn. It does add a random abstract cover to epub but nothing else.

Not sure if I should just comment out cover code or not? Not sure what I'm meant to do if cover is blocked.

This is novel I tested: https://www.asianhobbyist.com/series/my-%e3%80%90repair%e3%80%91skill-became-an-almighty-cheat-skill-so-i-thought-id-open-up-a-weapon-shop/

This is error I'm getting:
```
-- Logging error ---
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\downloader.py", line 122, in _fetch_cover_image  
    _fetch_content_image(
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\downloader.py", line 104, in _fetch_content_image
    img = app.crawler.download_image(url)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 237, in download_image
    response = self.__process_request("get", url, headers=headers, **kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 97, in __process_request
    raise e
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\scraper.py", line 91, in __process_request
    response.raise_for_status()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cdn.novelupdates.com/images/2019/05/321901000610.jpg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\User\Desktop\Github\lightnovel-crawler\lncrawl\core\downloader.py", line 128, in _fetch_cover_image
    logger.exception("Failed to download cover", e)
Message: 'Failed to download cover'
Arguments: (HTTPError('403 Client Error: Forbidden for url: https://cdn.novelupdates.com/images/2019/05/321901000610.jpg'),)
```

### CODE REVIEW

**Comment by dipu-bd** [comment]
You can try testing one of the new templates:

https://github.com/dipu-bd/lightnovel-crawler/tree/dev/sources/_examples

**Comment by idMysteries** [comment]
@dipu-bd 403 error for image? cloudflare?

**Comment by SirGryphin** [comment]
I don't think it's the template, I just think it's cloudflare from novelupdates site blocking it.

**Comment by dipu-bd** [comment]
I managed to integrate chrome browser as a interface finally. We have no more worry about cloudflare. 

Check for example: https://github.com/dipu-bd/lightnovel-crawler/blob/dev/sources/en/w/webnovel.py

**Comment by SirGryphin** [comment]
@dipu-bd Thanks I will have to have a play around with new templates and see what I can do. (noob at python)

Also not sure if I should make a bug report or not as it's dev, but novelfull doesn't show novel title. It just says "None".

**Comment by dipu-bd** [comment]
I will check this issue

**Comment by dipu-bd** [comment]
is this PR ready for merge, or do you want to improve it more?

**Comment by idMysteries** [comment]
@dipu-bd https://github.com/dipu-bd/lightnovel-crawler/blob/ec81b54893aa6d3ce07e4b8c4bcd431b70233fcd/sources/en/a/asianhobbyist.py#L38
is it ok?

**Comment by dipu-bd** [comment]
@idMysteries No. 

After new changes, assigning the `volume` is optional. Leave it empty @SirGryphin 

Why not use the `self.cleaner.extract_contents` in second case?

**Comment by idMysteries** [comment]
@dipu-bd 
What is the point of separating ```extract_contents``` and ```clean_contents```?

**Comment by SirGryphin** [comment]
@idMysteries I only updated a few line of the original source for it to get chapters and novel title. Everything else is from whoever made original file. But it's a moot point because cover is still linking to novelupdates which is blocked by cloudflare which means either disabling cover or redo whole source maybe with new templates.

**Comment by idMysteries** [comment]
> @idMysteries I only updated a few line of the original source for it to get chapters and novel title. Everything else is from whoever made original file. But it's a moot point because cover is still linking to novelupdates which is blocked by cloudflare which means either disabling cover or redo whole source maybe with new templates.

Leave the cover, it's not the problem of this crawler.

**Comment by dipu-bd** [comment]
> Is it possible to add a cloudflare detector to download covers via the browser?

Yes. You have to override the `download_image` method.

```py
    def download_image(self, url: str, headers={}, **kwargs) -> Image:
        try:
            content = super().download_image(url, headers, **kwargs)
        except ScraperErrorGroup:
            content = # logic to get the image content as bytes from the browser
        return Image.open(BytesIO(content))
```

**Comment by dipu-bd** [comment]
> What is the point of separating `extract_contents` and `clean_contents`?

`clean_contents` removes unwanted tags, css, etc keeping the original structure of the html untouched.

`extract_contents` restructures the entire thing to make paragraphs. 

It was necessary to leave the original structure untouched when scraping from a few sites in the past.

**Comment by SirGryphin** [comment]
@dipu-bd I don't know enough to override the image using the code you provided. As previously stated, I am a complete Python newbie; I can change, tweak, and google, but that is about it.

I'm not sure if you want to close this or merge it, but it's completely up to you. I could probably sit here and figure it out in a few hours, but I just don't have free time. I've been replying in between work.

In recap, asianhobbyist, everything works except the cover. myboxnovel everything working fine on that, but I did get a weird "pool is closed" error on one novel.

**Comment by dipu-bd** [comment]
> @dipu-bd I don't know enough to override the image using the code you provided. As previously stated, I am a complete Python newbie; I can change, tweak, and google, but that is about it.

You don't have to do that. I posted it as an example. Later I already added this feature to BasicBrowserTemplate. 

I am currently testing and preparing for v3 release. I will merge your PR soon

**Pull request merged**
